# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7f29c21bc9c0ffe8478c942209db6cb24be94cf7a645ea49e85766ae1052f399a217476c502e5e1d3f6761d74ef1dbd3a20dd79c7021326013eb264f5b7c5e

test:
  secret_key_base: c176ecdbef9732bcbd08e32cf56e57a9a5d51e83dd051f1d243ea71a3029ee8f61d9bb9cad8990768171b518c8de3c3f23658012bab245c16a53004f2eed0691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
